// WebView bootstrap script — exported as a string for injectedJavaScript.
// Handles session capture and generic embed video URL interception.

exports.GLOBAL_BOOTSTRAP = [
  "(function() {",
  "",
  "  var post = function(type, data) {",
  "    if (!window.ReactNativeWebView) return;",
  "    window.ReactNativeWebView.postMessage(JSON.stringify({ type: type, data: data }));",
  "  };",
  "",
  "  var log = function(msg) { post('LOG', msg); };",
  "",
  "  // Session Reporting - with Cloudflare detection",
  "  var reportSession = function() {",
  "    post('SESSION_UPDATE', {",
  "      cookies: document.cookie,",
  "      userAgent: navigator.userAgent",
  "    });",
  "  };",
  "",
  "  // Poll for Cloudflare validation instead of immediate report",
  "  var pollForCloudflareValidation = function() {",
  "    var maxAttempts = 150; // 15 seconds max (150 * 100ms)",
  "    var attempts = 0;",
  "    ",
  "    var check = function() {",
  "      attempts++;",
  "      var title = document.title || '';",
  "      var cookies = document.cookie || '';",
  "      var isCloudflarePage = title.indexOf('Just a moment') !== -1;",
  "      var hasCookies = cookies.length > 0;",
  "      ",
  "      if (!isCloudflarePage && hasCookies) {",
  "        reportSession();",
  "        return;",
  "      }",
  "      ",
  "      if (attempts >= maxAttempts) {",
  "        reportSession();",
  "        return;",
  "      }",
  "      ",
  "      setTimeout(check, 100);",
  "    };",
  "    ",
  "    check();",
  "  };",
  "",
  "  pollForCloudflareValidation();",
  "",
  "  // --- Generic Embed Video URL Interception ---",
  "  (function() {",
  "    if (window.__VIDEO_INTERCEPT_ACTIVE__) return;",
  "    window.__VIDEO_INTERCEPT_ACTIVE__ = true;",
  "    var origFetch = window.fetch;",
  "    var VIDEO_RE = /\\.(mp4|m3u8|webm|ogg)(\\?.*)?$/i;",
  "",
  "    window.fetch = function() {",
  "      var args = Array.prototype.slice.call(arguments);",
  "      var reqUrl = typeof args[0] === 'string' ? args[0] : args[0].url;",
  "      if (reqUrl && VIDEO_RE.test(reqUrl)) {",
  "        log('intercepted fetch: ' + reqUrl);",
  "        post('EMBED_VIDEO_URL', reqUrl);",
  "      }",
  "      return origFetch.apply(this, args);",
  "    };",
  "",
  "    var origXHROpen = XMLHttpRequest.prototype.open;",
  "    XMLHttpRequest.prototype.open = function(method, url) {",
  "      if (url && VIDEO_RE.test(url)) {",
  "        log('intercepted XHR: ' + url);",
  "        post('EMBED_VIDEO_URL', url);",
  "      }",
  "      return origXHROpen.apply(this, arguments);",
  "    };",
  "  })();",
  "})();",
  "true;"
].join("\n");
