export const GLOBAL_BOOTSTRAP = [
  "(function() {",
  "  var post = function(type, data) {",
  "    if (!window.ReactNativeWebView) return;",
  "    window.ReactNativeWebView.postMessage(JSON.stringify({ type: type, data: data }));",
  "  };",
  "",
  "  var reportSession = function() {",
  "    post('SESSION_UPDATE', {",
  "      cookies: document.cookie,",
  "      userAgent: navigator.userAgent",
  "    });",
  "  };",
  "",
  "  // A Cloudflare challenge page is a full HTML document whose body has no app",
  "  // content; matching its fingerprint survives localized titles.",
  "  var isChallengePage = function() {",
  "    var title = document.title || '';",
  "    if (title.indexOf('Just a moment') !== -1) return true;",
  "    if (title.indexOf('Attention Required') !== -1) return true;",
  "    if (document.getElementById('challenge-form')) return true;",
  "    if (document.getElementById('challenge-error-text')) return true;",
  "    if (document.getElementById('cf-challenge-running')) return true;",
  "    return false;",
  "  };",
  "",
  "  // Slow devices and multi-stage challenges can take well over 5s to clear.",
  "  // Reporting early ships an invalid session that guarantees 403s downstream.",
  "  // Aligned with the native 40s gate. Reports every update; native settles.",
  "  var pollForCloudflareValidation = function() {",
  "    var maxAttempts = 400;",
  "    var attempts = 0;",
  "    var last = '';",
  "    var check = function() {",
  "      attempts++;",
  "      if (!isChallengePage() && document.cookie.length > 0 && document.cookie !== last) {",
  "        last = document.cookie;",
  "        reportSession();",
  "      }",
  "      if (attempts >= maxAttempts) {",
  "        return;",
  "      }",
  "      setTimeout(check, 100);",
  "    };",
  "    check();",
  "  };",
  "",
  "  pollForCloudflareValidation();",
  "})();",
  "true;",
].join("\n");
