export const GLOBAL_BOOTSTRAP = [
  "(function() {",
  "  var post = function(type, data) {",
  "    if (!window.ReactNativeWebView) return;",
  "    window.ReactNativeWebView.postMessage(JSON.stringify({ type: type, data: data }));",
  "  };",
  "",
  "  var reportSession = function() {",
  "    post('SESSION_UPDATE', {",
  "      cookies: document.cookie,",
  "      userAgent: navigator.userAgent",
  "    });",
  "  };",
  "",
  "  var pollForCloudflareValidation = function() {",
  "    var maxAttempts = 50;",
  "    var attempts = 0;",
  "    var check = function() {",
  "      attempts++;",
  "      var title = document.title || '';",
  "      var cookies = document.cookie || '';",
  "      if (title.indexOf('Just a moment') === -1 && cookies.length > 0) {",
  "        reportSession();",
  "        return;",
  "      }",
  "      if (attempts >= maxAttempts) {",
  "        reportSession();",
  "        return;",
  "      }",
  "      setTimeout(check, 100);",
  "    };",
  "    check();",
  "  };",
  "",
  "  pollForCloudflareValidation();",
  "})();",
  "true;",
].join("\n");
